/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mCRUD = new javax.swing.JMenu();
        jMIInsertaJuego = new javax.swing.JMenuItem();
        jMIModificarJuego = new javax.swing.JMenuItem();
        jMIEliminarJuego = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        mReporte1 = new javax.swing.JMenu();
        mReporte2 = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mCRUD.setText("CRUD de juegos");

        jMIInsertaJuego.setText("Insertar  juego");
        jMIInsertaJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInsertaJuegoActionPerformed(evt);
            }
        });
        mCRUD.add(jMIInsertaJuego);

        jMIModificarJuego.setText("Modificar juego");
        jMIModificarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarJuegoActionPerformed(evt);
            }
        });
        mCRUD.add(jMIModificarJuego);

        jMIEliminarJuego.setText("Eliminar juego");
        jMIEliminarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEliminarJuegoActionPerformed(evt);
            }
        });
        mCRUD.add(jMIEliminarJuego);

        jMenuBar1.add(mCRUD);

        mReportes.setText("Reportes");

        mReporte1.setText("Reporte 1");
        mReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporte1ActionPerformed(evt);
            }
        });
        mReportes.add(mReporte1);

        mReporte2.setText("Reporte 2");
        mReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporte2ActionPerformed(evt);
            }
        });
        mReportes.add(mReporte2);

        jMenuBar1.add(mReportes);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIEliminarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEliminarJuegoActionPerformed
        EliminarJuego ventanaEliminarJuego = new EliminarJuego(this, true);
        ventanaEliminarJuego.setVisible(true);
    }//GEN-LAST:event_jMIEliminarJuegoActionPerformed

    private void jMIInsertaJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInsertaJuegoActionPerformed
        InsertarJuego ventanaInsertarJuego = new InsertarJuego(this, true);
        ventanaInsertarJuego.setVisible(true);
    }//GEN-LAST:event_jMIInsertaJuegoActionPerformed

    private void jMIModificarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarJuegoActionPerformed
        ModificarJuego ventanaModificarJuego = new ModificarJuego(this, true);
        ventanaModificarJuego.setVisible(true);
    }//GEN-LAST:event_jMIModificarJuegoActionPerformed

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mSalirMouseClicked

    private void mReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporte1ActionPerformed
        Reporte1 ventanaReporte1 = new Reporte1(this, true);
        ventanaReporte1.setVisible(true);
        
    }//GEN-LAST:event_mReporte1ActionPerformed

    private void mReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporte2ActionPerformed
        Reporte2 ventanaReporte2 = new Reporte2(this, true);
        ventanaReporte2.setVisible(true);
    }//GEN-LAST:event_mReporte2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMIEliminarJuego;
    private javax.swing.JMenuItem jMIInsertaJuego;
    private javax.swing.JMenuItem jMIModificarJuego;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCRUD;
    private javax.swing.JMenu mReporte1;
    private javax.swing.JMenu mReporte2;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mSalir;
    // End of variables declaration//GEN-END:variables
}
